springdoc:
    swagger-ui:
        enabled: true
    api-docs:
        version: "OPENAPI_3_0"
        enabled: true
keystore:
    password: ${KEYSTORE_PASSWORD}
trdm:
    props-path: ${CLIENT_PROPS_FILE_PATH}
    encryption-username: ${ENCRYPTION_USERNAME}


